# docker-compose-devcontainer.yml

services:
  backend:
    # Build with the local Dockerfile in .devcontainer
    build:
      context: ./backend/  # Path to the project's root folder
      dockerfile: Dockerfile.dev  # Path to the Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      # Mount the root folder that contains .git
      - .:/workspace:cached
    ports:
      # Django
      - 8002:8002

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
