server {
    listen 80;
    server_name wayfinder2.daniel.es;  # Change this to your domain name

    # React (npm build files)
    location / {
        root   /usr/share/nginx/html/frontend;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }


    # location /api/ {
    #     proxy_pass http://backend:8000;  # Replace with the name of your Django container
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    # }

    location /api {
    include proxy_params;
    proxy_pass http://localhost:8000;
}
}