# Generated by Django 5.0 on 2023-12-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder_timescale', '0002_alter_location_coordinates_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
