# Generated by Django 5.0 on 2023-12-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('geometry_type', models.CharField(max_length=50)),
                ('coordinates_longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('coordinates_latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('activity', models.CharField(max_length=50)),
                ('altitude', models.IntegerField()),
                ('battery_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('battery_state', models.CharField(max_length=50)),
                ('desired_accuracy', models.IntegerField()),
                ('device_id', models.CharField(max_length=50)),
                ('horizontal_accuracy', models.IntegerField()),
                ('locations_in_payload', models.IntegerField()),
                ('motion', models.CharField(blank=True, max_length=50)),
                ('pauses', models.BooleanField()),
                ('speed', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('tracking_mode', models.IntegerField()),
                ('vertical_accuracy', models.IntegerField()),
                ('wifi', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('geometry_type', models.CharField(max_length=50)),
                ('coordinates_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('coordinates_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('action', models.CharField(max_length=50)),
                ('arrival_datetime', models.DateTimeField()),
                ('battery_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('battery_state', models.CharField(max_length=50)),
                ('departure_datetime', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(max_length=50)),
                ('horizontal_accuracy', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('wifi', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
