# Generated by Django 5.1.1 on 2024-09-13 13:26

import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('altitude', models.IntegerField()),
                ('battery_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('battery_state', models.CharField(max_length=20)),
                ('course', models.IntegerField()),
                ('course_accuracy', models.IntegerField()),
                ('device_id', models.CharField(blank=True, max_length=50)),
                ('horizontal_accuracy', models.IntegerField()),
                ('motion', models.JSONField()),
                ('speed', models.IntegerField()),
                ('speed_accuracy', models.IntegerField()),
                ('unique_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vertical_accuracy', models.IntegerField()),
                ('wifi', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('altitude', models.IntegerField()),
                ('arrival_date', models.DateTimeField()),
                ('battery_level', models.DecimalField(decimal_places=2, max_digits=3)),
                ('battery_state', models.CharField(max_length=20)),
                ('departure_date', models.DateTimeField()),
                ('device_id', models.CharField(blank=True, max_length=50)),
                ('horizontal_accuracy', models.IntegerField()),
                ('unique_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vertical_accuracy', models.IntegerField()),
                ('wifi', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
