# Generated by Django 5.1.1 on 2024-09-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
