# Generated by Django 5.1.1 on 2024-09-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0002_alter_visit_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='course_accuracy',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='speed_accuracy',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
