# Generated by Django 5.1.1 on 2024-09-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0003_alter_location_course_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='altitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='vertical_accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
