# Generated by Django 5.1.1 on 2024-09-19 18:42

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Extract


def delete_null_departure_dates(apps, schema_editor):
    Visit = apps.get_model("wayfinder", "Visit")
    Visit.objects.filter(departure_date__isnull=True).delete()


def calculate_duration(apps, schema_editor):
    Visit = apps.get_model("wayfinder", "Visit")
    Visit.objects.update(
        duration=Extract(F("departure_date") - F("arrival_date"), "epoch")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wayfinder", "0004_alter_visit_altitude_alter_visit_vertical_accuracy"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="duration",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visit",
            name="departure_date",
            field=models.DateTimeField(),
        ),
        migrations.RunPython(delete_null_departure_dates),
        migrations.RunPython(calculate_duration),
    ]
