# Generated by Django 5.1.1 on 2024-09-22 20:36

from django.db import migrations, models
from decimal import Decimal, ROUND_HALF_UP


def convert_seconds_to_hours(apps, schema_editor):
    Visit = apps.get_model("wayfinder", "Visit")
    for visit in Visit.objects.all():
        if visit.duration is not None:
            # Convert seconds to hours and round to 2 decimal places
            hours = Decimal(visit.duration) / Decimal("3600")
            visit.duration = hours.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
            # Ensure the value doesn't exceed the field's maximum
            if visit.duration >= Decimal("10000"):
                visit.duration = Decimal("9999.99")
            visit.save()


def convert_hours_to_seconds(apps, schema_editor):
    Visit = apps.get_model("wayfinder", "Visit")
    for visit in Visit.objects.all():
        if visit.duration is not None:
            # Convert hours to seconds (rounding is not necessary here)
            visit.duration = int(Decimal(visit.duration) * Decimal("3600"))
            visit.save()


class Migration(migrations.Migration):

    dependencies = [
        ("wayfinder", "0005_visit_duration_alter_visit_departure_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="duration",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.RunPython(convert_seconds_to_hours, convert_hours_to_seconds),
    ]
