# Generated by hand because automated tooling unavailable in workspace

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wayfinder", "0007_alter_location_time_alter_visit_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="device_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="device_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                null=True,
            ),
        ),
    ]
