# Generated by Django 5.2.12 on 2026-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wayfinder', '0009_usersettings_dailyactivitysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivitysummary',
            name='partial',
            field=models.BooleanField(default=False),
        ),
    ]
